tutorials/setting-up-postgres.md

Fixed disaster recovery  plan link in setting up postgres tutorial.

Fixed disaster recovery plan link

---

tutorials/send-connect-notification-to-slack-from-google-compute-engine.md

Slack recommends creating an app rather than a custom integration.
https://medium.com/slack-developer-blog/one-way-to-get-started-a14b91280144#.dxb8nvdch

Update SSH Notification tutorial for new "internal integrations" flow.

---

tutorials/run-symfony-on-appengine-flexible/index.md

fixes mixed content in symfony tutorial

---

test/utils.js
tutorials/on-beyond-magpie0.md
tutorials/on-beyond-magpie1.md
tutorials/on-beyond-magpie2.md

A set of 3 tutorials aimed at Advanced Placement teachers but potentially valuable for anyone who wants to get started with the Cloud Natural Language API.
Since this is a set, they refer to each other and the links will need to be updated before publication.  I guessed at names as well as I could, but know I don't guess well.

Magpie patch 1

---

tutorials/send-email-with-sparkpost-and-nodejs-on-google-app-engine.md

Node.js flexible, Python standard and flexible samples are on the way too.

Adding SparkPost + Node.js on Google App Engine tutorial

---

tutorials/joomla-on-compute-engine.md

Minor style changes for tutorial

---

tutorials/developing-services-with-k8s.md

This tutorial walks through how to set up a local dev environment for the Guestbook sample app and GKE. There's lots of documentation on how to get something running in GKE, but not as much about how to actually *edit* your code. Feedback welcome!

Local development with GKE

---

tutorials/ssh-tunnel-on-gce.md

cc: @jimtravis feel free to patch my branch directly
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>

Add ssh-tunnel-on-gce tutorial

---

tutorials/setting-up-postgres.md

Issue with markdown formatting causing a heading to be displayed as a numbered list item.

Formatting fix

---

tutorials/docker-compose-on-container-optimized-os.md

This is needed to run the `docker-compose` command easily on a
locked-down system like Container-Optimized OS.
cc @ahmetb

Tutorial for running Docker Compose in Docker.

---

tutorials/run-swift-vapor-on-google-cloud/index.md

Make consistent with other Swift tutorials.

Fix comments pointing to future points.

---

tutorials/slack-slash-command-app-engine-java.md

This is a community tutorial around this sample:
https://github.com/GoogleCloudPlatform/slack-samples/tree/master/java/command

Running a Slack Slash Command on App Engine using Java

---

tutorials/cloud-functions-sns-pubsub/index.md

This was missed in final steps

Update SNS tutorial with inlined script contents

---

tutorials/bigtable-stackdriver/index.md

Misunderstood and thought local files were autopopulated.

Fix Bigtable Stackdriver links

---

tutorials/managing-gcp-projects-with-terraform/index.md

Removed "> Note.." format to try and fix the truncated site.

Trying to fix Managing GCP Projects tutorial.

---

tutorials/developing-services-with-k8s.md

This updates the tutorial to not require users to understand or write custom YAML, by using newer Telepresence functionality.
We've signed an organizational CLA (specifically, our CEO Richard Li did).
Thanks!

Update to using --swap-deployment, which is a more reasonable workflow.

---

tutorials/appengine-pusher/index.md

Thanks for fixing the other issues, found a few more.

fixing formatting issues

---

tutorials/grails3-send-push-notification-using-firebase-cloud-messaging/index.gsp
tutorials/grails3-send-push-notification-using-firebase-cloud-messaging/index.md

Create a new folder with index.md content copied from grails3-send-push-notification-using-firebase-cloud-messaging.md

Create grails3-send-push-notification-using-firebase-cloud-messaging (originally from #224)

---

tutorials/continuous-deployment-pipeline-google-container-engine-with-codeship/index.md

Correcting missed angle bracket issue with code examples.

fixing angle bracket issue

---

tutorials/using-cloud-vpn-with-cisco-asr/index.md

Updated as per inputs from kappamaki00.

Updated index.md

---

tutorials/setting-up-lamp.md

Adds correct LAMP instructions for Debian 8

---

tutorials/run-spring-petclinic-on-app-engine-cloudsql/index.md
tutorials/run-spring-petclinic-on-app-engine-cloudsql/spring-petclinic/src/main/resources/application-mysql.properties

fixing referencies to application properties files

---

tutorials/managing-gcp-projects-with-terraform/.gitignore
tutorials/managing-gcp-projects-with-terraform/compute.tf
tutorials/managing-gcp-projects-with-terraform/index.md
tutorials/managing-gcp-projects-with-terraform/project.tf

Updated tutorial and source to work with latest gcloud and Terraform versions.

[tutorials/managing-projects-with-terraform] Update tutorial with latest commands

---

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/.dockerignore
tutorials/elixir-phoenix-on-kubernetes-google-container-engine/Dockerfile
tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md

This is a new tutorial on deploying an application written in Elixir using the Phoenix framework to Container Engine.
Subject matter review may be assigned to any or all of: @JustinBeckwith @bshaffer @chingor13

New Tutorial - Deploying an Elixir Phoenix app to GKE

---

tutorials/styleguide.md

These were things I didn't know about, they could be documented in the style guide.

Document GFM specifics, HTML stripping, and EmbedMd usage.

---

tutorials/elixir-phoenix-on-google-compute-engine/Dockerfile
tutorials/elixir-phoenix-on-google-compute-engine/index.md
tutorials/elixir-phoenix-on-google-compute-engine/instance-startup.sh

This is a new tutorial on deploying an application written in Elixir using the Phoenix framework to Container Engine.
Parts of the content (especially the sections on load balancing and autoscaling) were adapted from the standard Bookshelf-GCE tutorials (e.g. https://cloud.google.com/ruby/tutorials/bookshelf-on-compute-engine).
Subject matter review may be assigned to any or all of: @JustinBeckwith @bshaffer @chingor13

New Tutorial - Deploying an Elixir Phoenix app to GCE

---

tutorials/run-laravel-on-appengine-flexible/index.md

removes duplicate APP_LOG

---

tutorials/run-symfony-on-appengine-flexible/index.md

Symfony: Add Doctrine for CloudSQL

---

tutorials/appengine-serve-machine-learning-model/index.md

Correct typo

---

tutorials/cloud-functions-oauth-gmail/index.js
tutorials/cloud-functions-oauth-gmail/index.md
tutorials/cloud-functions-oauth-gmail/package.json

Add OAuth + GCF tutorial

---

tutorials/github-auto-assign-reviewers-cloud-functions/index.md

Fixes typo

---

tutorials/kotlin-springboot-compute-engine.md

New Tutorial: Kotlin Spring Boot on Google Compute Engine

---

tutorials/kotlin-springboot-container-engine.md

Added Kotlin Spring Boot Container Engine Tutorial

---

tutorials/cloud-functions-sns-pubsub/index.js
tutorials/cloud-functions-sns-pubsub/index.md
tutorials/iot-device-to-device/index.md

removed beta flag from gcloud pubsub api

updated client library api to 0.16.4

---

tutorials/kotlin-springboot-app-engine.md
tutorials/kotlin-springboot-app-engine/index.md
tutorials/kotlin-springboot-app-engine/pom-plugin-example.xml

New Tutorial: Kotlin Spring Boot on Google App Engine

---

tutorials/nginx-ingress-gke/index.md

nginx-ingress-gke: Small fixes

---

tutorials/setting-up-postgres.md

There is a lack of information, it is needed to create a rule with Direction of traffic as Ingress and another rule as Egress to enable remote access.

Update section "Open the network port"

---

tutorials/managing-gcp-projects-with-terraform/index.md

services -> service-management

Adjust for latest gcloud commands.

---

tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md

Changing from gcloud app deploy to gcloud beta app deploy

Fixing deploy command for endpoints tutorial

---

tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md

Fixed author's github username

Fixing github username

---

tutorials/google-kubernetes-engine-hyperparameter-search/index.md

This is an accompanying content for these code samples: https://github.com/GoogleCloudPlatform/ml-on-gcp/tree/master/sklearn/hpsearch

Scikit-learn hyperparameter search on GKE

---

tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md

Updated the date to reflect today's date

Updated the date to reflect today's date

---

tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md

Updated formatting and hyperlink

Updated formatting and hyperlink

---

tutorials/managing-gcp-projects-with-terraform/index.md

Replaced depreciated cli method

Swap services-management for services

---

tutorials/using-cloud-vpn-with-checkpoint/index.md

- Updated Phase-2 integrity to include `sha-256` as this is offered in the proposal
- Added Phase-2 lifetime

[Cloud VPN with Checkpoint] Phase-2 parameter updates

---

tutorials/automated-publishing-cloud-build/index.md

Change "Cloud Builder" to "Cloud Build"

---

tutorials/bigquery-ibis/ibis_bigquery.py
tutorials/bigquery-ibis/index.md
tutorials/bigquery-ibis/requirements.txt

This tutorial demonstrates how to make BigQuery queries with using
Python as a replacement for SQL with the Ibis library.
/CC @cpcloud

Querying BigQuery with Ibis tutorial.

---

resources/templates/index.md
resources/templates/vpn-interop-guide-template/index.md

This index.md file is the template for creating new VPN interop guides.

Create vpn-interop-guide-template file

---

tutorials/kotlin-springboot-app-engine/index.md

Misc fixes to kotlin sample

---

resources/templates/vpn-interop-guide-template/index.md

Fixed URLs for links to GCP console

Update VPN interop template

---

tutorials/appengine-dropwizard/index.md

Dropwizard is not an Apache project, I confused with Apache licence.

Replace  'Apache Dropwizard' with just 'Dropwizard'

---

tutorials/gke-filestore-dynamic-provisioning/index.md

The code lines rendered fine in the GitHub preview but not on cloud.google.com.

fixing number of spaces in code indentation

---

tutorials/using-cloud-vpn-with-alibaba-site-to-site/index.md

In this pass, I converted the image link and tables to Markdown.
I'll do a final detail pass tomorrow.

first production pass

---

tutorials/setting-up-postgres-hot-standby.md

fixing typo reported in bug

---

tutorials/pubsub-logging-pvm-shutdowns/index.md

fixing typo reported here:
https://github.com/GoogleCloudPlatform/community/issues/398

fixing typo

---

tutorials/cloud-iot-gateways-rpi/cloudiot_mqtt_gateway.py

Moved subscribe to connect handler.  Was having issues with it being called right after connect.  Also this allows for re-connect attempts (which I also added) to also re-subscribe.

made MQTT gateway script more robust

---

tutorials/run-symfony-on-appengine-standard/index.md

Somehow the doctrine section of this was not updated from the flex tutorial. This is now fixed.

Fixes symfony tutorial

---

tutorials/run-hapijs-on-google-app-engine.md

This converts a codeblock to use the indentation style required by our quirky publishing system. I also fixed a couple of other minor issues.

fixing codeblock that rendered as body text

---

tutorials/run-meteor-on-google-app-engine.md

This converts codeblocks to use the indentation style required by our quirky publishing system. I also fixed a couple of other minor issues.

fixing codeblocks that appeared as body text

---

tutorials/appengine-python-api-firebase-auth/index.md
tutorials/appengine-ruby-rails-activejob-pubsub.md
tutorials/bigquery-from-excel/index.md
tutorials/deploy-grails-to-google-cloud/index.md
tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md
tutorials/express-memcached-session-appengine/index.md
tutorials/extending-google-appengine-flexible-nodejs-runtime/index.md
tutorials/kotlin-ktor-app-engine-java8/index.md
tutorials/kotlin-springboot-app-engine-java8/index.md
tutorials/kotlin-springboot-app-engine/index.md
tutorials/kotlin-springboot-compute-engine.md
tutorials/kotlin-springboot-container-engine.md
tutorials/kubernetes-auth-openid-rbac.md
tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md
tutorials/nodejs-mongodb-on-appengine.md
tutorials/nodejs-parse-server-on-appengine.md
tutorials/nodejs-redis-on-appengine.md
tutorials/run-swift-kitura-on-google-cloud/index.md
tutorials/run-symfony-on-appengine-flexible/index.md
tutorials/send-email-with-mailgun-and-nodejs-on-google-app-engine.md
tutorials/send-email-with-sendgrid-and-nodejs-on-google-app-engine.md
tutorials/send-email-with-sparkpost-and-nodejs-on-google-app-engine.md
tutorials/use-cloud-pubsub-cloud-storage-app-engine/index.md
tutorials/zero-to-deploy-with-chef.md
tutorials/zero-to-lamp-deploy-with-chef/index.md

This PR fixes codeblocks that were appearing as plain text with Markdown commands.
I also fixed several (but not all) instances of incorrect uses of Google product names. Because the main purpose of this PR is to fix the codeblocks, I mostly just fixed the bad uses of product names in titles and other very obvious places.

fixing badly formatted codeblocks and branding in titles

---

tutorials/managing-gcp-projects-with-terraform/index.md

Running terraform init after all .tf files are defined gives terraform a list of all needed plugins.

Posponed terraform init

---

tutorials/using-cloud-vpn-with-checkpoint/index.md

Adjusting keepalive/hold timers per official docs:
https://cloud.google.com/router/docs/concepts/overview#timer-settings

BGP keepalive/hold timers for Checkpoint

---

tutorials/run-symfony-on-appengine-standard/index.md

Fixes Symfony Tutorial link to file

---

tutorials/cloudbuild-angular-universal/index.md

Codefences within numbered lists are not treated correctly by our publishing system, so I converted the problematic codeblocks to use indentation instead.

fixing codeblocks

---

tutorials/cloud-iot-gateways-rpi/cloudiot_mqtt_gateway.py
tutorials/cloud-iot-gateways-rpi/index.md
tutorials/cloud-iot-gateways-rpi/run-gateway

- Removed whitespaces 
- Cleaned up gateway client by removing/fixing unused arguments
- Add clearer line numbers references in `index.md` and fixed some bad links

iot: removed unused arguments from gateway client, update md links

---

tutorials/cloudbuild-angular-universal/index.md

Because our HTML sanitizer strips angle brackets and the contents between them, I escaped a set of them.
As long as I was in the file, I fixed some copy-editing issues.

escaping angle brackets

---

tutorials/get-started-bitnami-django.md
tutorials/install-bower-dependencies-on-google-app-engine.md
tutorials/ios-chatbot-part-2/index.md
tutorials/ios-chatbot-part-3/index.md
tutorials/iot-device-to-device/index.md
tutorials/kubernetes-auth-openid-rbac.md

Because our HTML sanitizer strips angle brackets and the contents between them, I need to escape some and replace others with square brackets.
Since I was in the files, I made some branding fixes and copy-editing fixes.

another batch of angle bracket fixes

---

archived/setting-up-lemp.md
tutorials/on-beyond-magpie2.md
tutorials/puppet-in-google-cloud-platform.md
tutorials/run-botkit-on-google-container-engine/index.md
tutorials/setting-up-postgres-hot-standby.md
tutorials/setting-up-postgres.md
tutorials/setting-up-ruby-discourse.md
tutorials/ssh-tunnel-on-gce.md
tutorials/using-cloud-vpn-with-cisco-asr/index.md
tutorials/wix-media-python.md

Because our HTML sanitizer strips angle brackets and the contents between them, I escaped some angle brackets, replaced others with square brackets, and removed a few outright.
While I was in the files, I did some basic branding and copy-editing cleanup.

dealing with angle brackets

---

tutorials/dotnet-mvms-quickstart.md
tutorials/exporting-stackdriver-elasticcloud/index.md
tutorials/gcp-cos-basic-fim/index.md
tutorials/gcp-cos-clamav/index.md
tutorials/java-gae-quickstart.md
tutorials/nodejs-gae-quickstart.md
tutorials/php-gae-quickstart.md
tutorials/php-mvms-quickstart.md
tutorials/python-gae-quickstart.md
tutorials/python-mvms-quickstart.md
tutorials/ruby-mvms-quickstart.md

There were some extraneous line breaks and bad tag in the staged documents. 
I also added links in the Container-Optimized OS documents for folks reading these documents on c.g.c., not GitHub. Without these links, the reader had no easy way of seeing the code.

fixing production issues found on staging

---

tutorials/exporting-stackdriver-elasticcloud/index.md

I'm troubleshooting an issue with this page's metadata.

minor tweak as part of troubleshooting investigation

---

tutorials/bigtable-oc/index.md
tutorials/bigtable-oc/java/pom.xml
tutorials/bigtable-oc/java/src/main/java/com/example/bigtable/App.java

This PR adds the files from this previous PR:
https://github.com/GoogleCloudPlatform/community/pull/813
The previous PR couldn't be reopened because the branch underlying it was deleted.

re-adding Drew's Bigtable tutorial

---

tutorials/cloud-iot-firestore-config/functions/package.json
tutorials/cloud-iot-firestore-config/functions/src/index.ts

Hi, @ptone 
by making the two changes,
I was able to make the 'npm install' working again.
I'll refactor more later on by using the: @google-cloud/iot library

Npm build issues fix

---

tutorials/php-gae-quickstart.md

made consistent with other tutorials

improved reference to Navigation menu

---

tutorials/use-cloud-pubsub-cloud-storage-app-engine/index.md
tutorials/use-cloud-pubsub-cloud-storage-app-engine/shared-photo-album-app/requirements.txt

See this entry for details of the vulnerability being addressed:
https://nvd.nist.gov/vuln/detail/CVE-2019-10906

addressing security vulnerability in Jinja

---

tutorials/cloudbuild-test-runner.md

I removed a call to action that was misplaced, and I did some copy-editing since I had the file open.

removing problematic link and call to action

---

tutorials/appengine-designing-for-scale.md

updating video link

---

tutorials/memorystore-oc/index.md

fixing broken link

---

tutorials/bigtable-stackdriver/index.md

fixed four broken links and did a little branding-related copy-editing

fixed broken links

---

tutorials/using-cloud-vpn-with-cisco-asr/index.md

fixes https://github.com/GoogleCloudPlatform/community/issues/761

fixing indentation that caused incorrect rendering of code blocks

---

tutorials/run-restifyjs-on-google-app-engine.md

refer from https://www.npmjs.com/package/restify

restify.js API changed.

---

tutorials/create-cloud-build-image-factory-using-packer/index.md

Makes a few small editorial changes.

Make small typo and punctuation fixes.

---

tutorials/managing-gcp-projects-with-terraform/index.md

Correct reference to credentials.

Updates for test pass in May 2019.

---

tutorials/appengine-pusher/java/pom.xml

details:
https://nvd.nist.gov/vuln/detail/CVE-2019-12086

updating jackson-databind version to deal with vulnerability

---

tutorials/run-swift-perfect-on-google-cloud/index.md
tutorials/run-swift-vapor-on-google-cloud/index.md

s/package/Package for Swift tutorials

---

tutorials/private-forseti-with-scc-integration/index.md

- fixed first two lists
- fixed placement of an image
- consolidated some steps

various production fixes

---

tutorials/cloud-functions-oauth-gmail/index.md

Customer reported issue with old auth URL that I reproduced. This fixes that.

Fix auth URL

---

tutorials/setting-up-loraserver.md

This updates:
* LoRa Server to v3 + update config examples.
* Refactors the Cloud Function from JS to Go.

Update LoRa Server tutorial.

---

tutorials/using-cloud-vpn-with-cisco-asr/index.md

adding line break

---

tutorials/stackdriver-monitor-slow-query-mysql/index.md

change author's name into github ID

change author's name into github ID

---

tutorials/pci-tokenizer/config/default.json

Using key and keyring names found in the solution published here:
https://cloud.google.com/solutions/tokenizing-sensitive-cardholder-data-for-pci-dss

Updating keyring config to match solution paper

---

tutorials/appengine-pusher/java/pom.xml

This fix addresses this vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2019-12814

updating jackson-databind to deal with security vulnerability

---

tutorials/elixir-phoenix-on-google-app-engine.md

Addresses lingering confusion around #940.

Update GAE-Elixir tutorial to cover changes in Elixir 1.9

---

tutorials/elixir-phoenix-on-google-compute-engine/.dockerignore
tutorials/elixir-phoenix-on-google-compute-engine/Dockerfile
tutorials/elixir-phoenix-on-google-compute-engine/index.md

This includes two updates:
* Modifies the build procedure according to feedback described in #774
* Adjusts some commands to reflect changes in Distillery 2.1 (cf. #968)

Update GCE-Elixir tutorial to improve build procedure

---

tutorials/stackdriver-monitor-slow-query-mysql/index.md

Link to @jpatokal, not "jani".

Correct author's Github username

---

tutorials/private-forseti-with-scc-integration/index.md

fixed backslash on command example

private-forseti-with-scc-integration

---

tutorials/cloud-functions-firestore/index.md

This flag is required for 1st time function deployments
https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--runtime

Add  --runtime=nodejs10 flag

---

tutorials/kotlin-springboot-compute-engine.md

The sample code is no longer available.
I also did a quick copy edit and fixed a mistaken reference to Google Kubernetes Engine.

removed references to downloadable sample code

---

tutorials/run-hapijs-on-google-app-engine.md

Updates to support the latest version of Hapi

Updates to support the latest version of Hapi

---

tutorials/appengine-pusher/java/pom.xml

https://nvd.nist.gov/vuln/detail/CVE-2019-14540
https://nvd.nist.gov/vuln/detail/CVE-2019-16335

addressing  security vulnerabilities

---

tutorials/bigquery-ibis/index.md

BigQuery is the approved name.

Changes 'Google BigQuery' to 'BigQuery'.

---

tutorials/puppet-in-google-cloud-platform.md

[Fix] Example contains syntax error

---

tutorials/cloud-iot-prometheus-monitoring/index.md
tutorials/compute-quickstart.md
tutorials/compute-short-quickstart.md
tutorials/iot-core-quickstart.md
tutorials/python-gae-quickstart.md

These changes update the format of variables and set their initial values in some cases that were causing our publishing system to complain.
related to these internal CLs:
280301873
277776242

updating variables to comply with publishing system

---

tutorials/cloud-pubsub-drainer/index.md

fixed typo

---

tutorials/gke-filestore-dynamic-provisioning/index.md

the reserved IP range gave an error, but worked fine if I removed the following: reserved-ip-range="10.0.0.0/29"
location was changed to zone.
I was also able to run these steps with helm version3. I'll be happy to streamline lots in here after helm v3 is released, (currently in RC3) :)

couple of changes to make the directions work

---

tutorials/dnssec-cloud-dns-domains/index.md

removing reference to defunct organization

---

tutorials/managing-gcp-projects-with-terraform/compute.tf
tutorials/managing-gcp-projects-with-terraform/index.md
tutorials/managing-gcp-projects-with-terraform/project.tf

 Terraform manage project 

---

tutorials/pci-tokenizer/Dockerfile
tutorials/pci-tokenizer/config/default.json
tutorials/pci-tokenizer/examples/wrapkey
tutorials/pci-tokenizer/index.md
tutorials/pci-tokenizer/package.json
tutorials/pci-tokenizer/src/app.js
tutorials/pci-tokenizer/src/server.js

Raw KMS is back by popular demand. Now you can choose between deterministic-but-CSEK DLP and non-deterministic-but-fully-managed-key KMS encryption.

Now supporting KMS and DLP tokenization

---

tutorials/network-throughput.md

We decided to launch a tool version of gcping.com 
so the users don't have to deal with a browser on a server.

Suggest gcping tool instead of the website

---

tutorials/getting-started-on-gcp-with-terraform/index.md

fixes https://github.com/GoogleCloudPlatform/community/issues/1139

Add example curl command to validate server

---

tutorials/run-laravel-on-appengine-standard/index.md
tutorials/setting-up-redis.md

[fix] clarify use of DB_SOCKET vs. DB_HOST

---

tutorials/kotlin-ktor-app-engine-java8/index.md

Fixes https://github.com/GoogleCloudPlatform/kotlin-samples/issues/52

Update gradle plugin version for appengine ktor sample

---

tutorials/bigtable-oc/java/src/main/java/com/example/bigtable/App.java

M_READ_LATENCY_MS was measuring writes
M_WRITE_LATENCY_MS was measuring reads

Fix read/write mixup

---

tutorials/getting-started-on-gcp-with-terraform/index.md

fixes https://github.com/GoogleCloudPlatform/community/issues/1167

Updating Terraform tutorial to use Terraform 0.12 syntax

---

tutorials/nginx-ingress-gke/index.md

updated nginx-ingress-tutorial/index.md

---

tutorials/stackdriver-monitor-slow-query-mysql/index.md

fixing link

---

tutorials/appengine-serve-machine-learning-model/index.md

Related to #1130, #1204 issues

invalid links fixed

---

tutorials/web-instrumentation/index.md

Removed extra line
import {CollectorExporter} from '@opentelemetry/exporter-collector';

Removed duplicate line

---

tutorials/cloud-iot-gateways-rpi/index.md
tutorials/cloud-iot-gateways-rpi/run-gateway

fix run-gateway script and upgrade to python3 venv

---

tutorials/visualizing-metrics-with-grafana/index.md

Added istio and helm install instructions

Istio and helm install instructions

---

tutorials/gke-workload-id-clientserver/index.md

Also deletes a bunch of trailing whitespace that my editor removed automatically.

Update IAM branding.

---

tutorials/continuous-deployment-pipeline-google-container-engine-with-codeship/index.md

fixes https://github.com/GoogleCloudPlatform/community/issues/1295

fixed product names and did some copy editing

---

tutorials/building-flask-api-with-cloud-firestore-and-deploying-to-cloud-run.md

removing outdated link

---

tutorials/setting-up-lamp/index.md

fixing issue #1255, php-mysql installation

---

tutorials/building-flask-api-with-cloud-firestore-and-deploying-to-cloud-run.md

Thanks to @hitezh for finding the typo at the end of the document.

fixed typo and updated some branding

---

tutorials/pci-tokenizer/index.js
tutorials/pci-tokenizer/package.json
tutorials/pci-tokenizer/src/app.js

Minor updates to work with the latest Cloud Functions
b/160952811

Updating for latest Cloud Functions architecture

---

CONTRIBUTORS
tutorials/load-testing-iot-using-gcp-and-locust/gke/locust-worker-set.template.yaml

Modified worker StatefulSet deployment template to create pods in parallel.

Resolves #1347, Modify StatefulSet to deploy in parallel

---

tutorials/get-started-bitnami-django.md

Updated get-started-bitnami-django.md

---

tutorials/cloud-run-with-pomerium-for-end-user-access/index.md

- Update image so that users always get the latest version
- Minor markdown table formatting fix
/cc @ahmetb @desimone

pomerium: update image source to point at 'latest'

---

tutorials/run-wordpress-on-appengine-standard/index.md

Fix typo in shell command

---

tutorials/gke-networking-fundamentals/index.md

kubectl run with --restart=Always no longer creates a deployment

Create deployment fix 

---

tutorials/datacatalog-tag-history/index.md

add the missing `\` in the command.

Fix the pipeline launch command

---

tutorials/cloud-functions-twilio-sms/index.md

tutorials/cloud-functions-twilio-sms: Fix gcloud functions logs read 

---

tutorials/joomla-on-compute-engine.md

Refreshing this tutorial as part of b/171430598 work. Also to address #1067

Updated joomla-on-compute-engine tutorial

---

tutorials/drupal-on-compute-engine.md

Refreshing this tutorial as part of b/171430598 work. Also to address #1432

Updated drupal-on-compute-engine tutorial

---

tutorials/cloud-run-local-dev-docker-compose/index.md

fix(cloud-run-local-dev-docker-compose): update for sql proxy 1.17+

---

tutorials/setting-up-postgres.md

Refreshing this tutorial as part of b/171430598 work. Also to address #769

Updated setting-up-postgres tutorial

---

tutorials/horizontally-scale-mysql-database-backend-with-google-cloud-sql-and-proxysql/index.md

fixes #1484 and many formatting errors

fixing issue 1484 and many formatting errors

---

tutorials/pubsub-spring-dedup-messages/index.md

Fixes #1471 
Thank you @ToddKopriva for forwarding! This should fix it!

fix git clone repo url in pubsub-spring-dedup-messages

---

tutorials/metrics-export-with-mql/index.md

removed extraneous Google

---

tutorials/write.md

broadening scope to other documents

---

tutorials/data-science-extraction/index.md

update sound file reference to archive.org

---

tutorials/building-flask-api-with-cloud-firestore-and-deploying-to-cloud-run.md

"implementation" typos

---

tutorials/gcp-cos-clamav/start.py

Now that you can import configs, added the ability to define your own cron schedule in the settings file `crontab`.

Adding support for custom cron config

---

tutorials/ml-pipeline-with-workflows/index.md

- This tutorial also uses bigquery, so I also added the command gcloud services enable bigquery.googleapis.com

Added command to enable requiring service api

---

tutorials/appengine-nodejs-webpack/package.json

https://github.com/advisories/GHSA-p493-635q-r6gr

updating pug version to avoid security issue

---

tutorials/antho-bare-metal-getting-started.md
tutorials/cloud-storage-bucket-lifecycle.md

Spelling updates

---

tutorials/metrics-export-with-mql/main.py

To fix the issue (#1619) that the token reusing optimization doesn't work with short interval schedule.

fix token expiration issue

---

tutorials/secrets-manager-python/index.md

fixes this issue:
https://github.com/GoogleCloudPlatform/community/issues/1633

updated code to match source

---

tutorials/managing-gcp-projects-with-terraform/index.md

Clarify tutorial purpose.

---

tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md

fixes this issue:
https://github.com/GoogleCloudPlatform/community/issues/1160

adding cost information

---

tutorials/cloud-asset-inventory-auto-label-resources/index.md

Fixed git pull command, cd argument (that's wrong after being merged), and ORGANIZATION_ID variable for the delete feed command.

Fixed git pull command, cd argument, and ORGANIZATION_ID variable

---

tutorials/bigquery-ibis/ibis_bigquery.py
tutorials/bigquery-ibis/index.md
tutorials/bigquery-ibis/requirements.txt

feat: use new ibis-bigquery package for latest bug fixes

---

tutorials/vm-migration-with-stratozone/index.md

Stratozone doc site no longer up. Added deep links to Google Docs.

fixes #1773 (broken links)

---

tutorials/appengine-angular-nginx-docker/index.md

To address https://github.com/GoogleCloudPlatform/community/issues/1814

Update index.md to address https://github.com/GoogleCloudPlatform/community/issues/1814

---

tutorials/using-scheduler-invoke-private-functions-oidc/index.md

fyi @dinagraves 
Minor updates to using-scheduler-invoke-private-functions-oidc
* Update functions-framework version, including new invocation method
* Update Python version used
* Enable Cloud Build is enabled (required service)
* Add commandline-based service enable method
* Add commandline-based function testing method
* Update author byline to include both authors.

maintenance update for using-scheduler-invoke-private-functions-oidc

---

tutorials/run-wordpress-on-appengine-standard/index.md

fix: incorrect wordpress summary

---

tutorials/nginx-ingress-gke/index.md

Ingress-nginx helm chart has moved into the sub project repo here https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

Update the helm chart to new spot

---

tutorials/deploy-react-nginx-cloud-run/Dockerfile
tutorials/deploy-react-nginx-cloud-run/index.md
tutorials/deploy-react-nginx-cloud-run/package.json

Also, issues: #1828 and #1406 can be closed.
Note: there are some warnings due to the dependency of react-scripts. Hopefully they will be fixed in a future react release. For now, they can be ignored.

refresh the react cloud run tutorial

---

tutorials/cloud-functions-firestore/index.js
tutorials/cloud-functions-firestore/index.md
tutorials/cloud-functions-firestore/package.json

Update tutorial: Use Firestore with Cloud Functions

---

tutorials/bigtable-oc/index.md
tutorials/bigtable-oc/java/pom.xml
tutorials/bigtable-oc/java/src/main/java/com/example/bigtable/App.java

update the bigtable-oc tutorial

---

tutorials/writing-prometheus-metrics-bigquery/index.md

Update the link of the sample code for this tutorial.

Update index.md of "Write Prometheus metrics to BigQuery" tutorial

---

tutorials/setting-up-postgres.md

"CREATE INSTANCE" button on the top:

The button says "CREATE INSTANCE", not just "CREATE"

---

tutorials/docker-gcplogs-driver/index.md

fixes this:
https://github.com/GoogleCloudPlatform/community/issues/762

updating to match new user interface; brief copy-edit

---

tutorials/nginx-ingress-gke/index.md

Updates to nginx ingress gke tutorial

---

tutorials/kubernetes-engine-customize-fluentbit/index.md
tutorials/kubernetes-engine-customize-fluentbit/kubernetes/fluentbit-daemonset.yaml

update cluster cmd and fluent image

---

tutorials/setting-up-lamp/index.md

Because of a change of UI, I updated the steps to create VM instances.
#1981

Updating the Create new VM instance steps

---

tutorials/setting-up-postgres.md

Step updated to match the new UI and include the "Source filter" menu: 
https://github.com/GoogleCloudPlatform/community/issues/1986

Update setting-up-postgres.md per new UI

---

tutorials/dataflow-dlp-to-datacatalog-tags/pom.xml

Several versions updated for the dataflow-dlp-to-datacatalog-tags tutorial

updating pom.xml lib versions

---

tutorials/understanding-oauth2-and-deploy-a-basic-auth-srv-to-cloud-functions/index.md

fixes this issue:
https://github.com/GoogleCloudPlatform/community/issues/2025

copy-edit and fix of function name

---

tutorials/terraform-asm-mcp.md

Overhaul of existing tutorial

---

tutorials/kubernetes-engine-customize-fluentbit/index.md
tutorials/kubernetes-engine-customize-fluentbit/kubernetes/test-logger.yaml
tutorials/kubernetes-engine-customize-fluentbit/test-logger/Dockerfile

Ask users to build the test-logger image to address b/210109504.

[update]Customizing Fluent Bit for Google Kubernetes Engine logs

---

tutorials/terraform-asm-mcp.md

Bumping the displayed publish date to the publication date of the revised tutorial. Changing this date will make it clear that the revised tutorial customers were waiting for was not previously available for months.
attn @alizaidis

Updating publish date

---

tutorials/serverless-vpc-access-private-mongodb-atlas/index.md

fix type in connection string by adding -pri

---

tutorials/cbt-import-csv.md

We have a new tool to import CSV files which is much easier than this, so I made a note at the start for people to use that instead of this tutorial

Update Bigtable CSV tutorial

---

tutorials/bigquery-ibis/index.md

This PR fixes broken links and outdated prose.

docs: fix broken links and outdated sqlalchemy blurb

---

tutorials/nginx-reverse-proxy-docker.md

tells the reader to establish an SSH connection

adding context for running the commands

---

tutorials/kubernetes-engine-customize-fluentbit/index.md
tutorials/kubernetes-engine-customize-fluentbit/kubernetes/fluentbit-configmap.yaml
tutorials/kubernetes-engine-customize-fluentbit/kubernetes/fluentbit-daemonset.yaml
tutorials/kubernetes-engine-customize-fluentbit/test-logger/logger.go

Minor updates for the kubernetes-engine-customize-fluentbit tutorial.

update fluentbit version etc.

---

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/Dockerfile

https://github.com/GoogleCloudPlatform/community/issues/1979

updated reference to nodejs-npm

---

tutorials/cloud-functions-async/index.md

word correction

---

tutorials/using-scheduler-invoke-private-functions-oidc/index.md

* App Engine no longer required for Cloud Scheduler
* Bump functions-framework, update sample output
* Update scheduler input to match command line, with UI updates

Maintenance update for OIDC tutorial

---

tutorials/speech2srt/requirements.txt

This should have been updated in 7919060b3f840bf9be930b6fc8c02452371f9516

speech2srt: update to latest google-cloud-speech (2.16.2)

---

tutorials/serverless-grafana-with-iap/code/main.tf

Grafana seems to have changed the defaults for user auto sign up

Updated environment config for Grafana

---

tutorials/migrate-oracle-postgres-using-datastream/index.md

1. some typos
2. some environment variables
3. create vpc-peering network before cloud sql created
4. change orders of execution

modified some errors

---

tutorials/serverless-grafana-with-iap/code/main.tf

Thanks @saimanwong for finding the issue and providing a solution

Fix for #2316, allowing all users invocation on the Cloud Run service.

---

tutorials/writing-prometheus-metrics-bigquery/index.md

Removed  the -  Learn how to
[manage Cloud Monitoring dashboards with the Cloud Monitoring API](/solutions/managing-monitoring-dashboards-automatically-using-the-api) bit because we archived the content.

Update index.md to remove links to archived content

---

tutorials/cloud-functions-avro-import-bq/index.js
tutorials/dlp-hybrid-inspect/src/main/java/com/example/dlp/HybridInspectSql.java
tutorials/dlp-to-datacatalog-tags/src/main/java/com/example/dlp/DlpDataCatalogTagsTutorial.java
tutorials/gcp-cos-basic-fim/scan.sh
tutorials/ml-pipeline-with-workflows/babyweight_model/trainer/model.py
tutorials/ml-pipeline-with-workflows/services/preprocess/main.py
tutorials/ml-pipeline-with-workflows/services/train/main.py
tutorials/pci-tokenizer/index.js
tutorials/pci-tokenizer/src/app.js
tutorials/prestashop-gke/php-nginx/7.3-fpm-alpine/config/php-fpm/php-fpm.d/www.conf

- Comment update in tutorials/cloud-functions-avro-import-bq/index.js
- Comments updates in tutorials/dlp-hybrid-inspect/src/main/java/com/example/dlp/HybridInspectSql.java
- Comment update in tutorials/dlp-to-datacatalog-tags/src/main/java/com/example/dlp/DlpDataCatalogTagsTutorial.java
- Message update in update in tutorials/gcp-cos-basic-fim/scan.sh
- Comment update in tutorials/ml-pipeline-with-workflows/babyweight_model/trainer/model.py
- Message update in tutorials/ml-pipeline-with-workflows/services/preprocess/main.py
- Message update in tutorials/ml-pipeline-with-workflows/services/train/main.py
- Comment update in tutorials/pci-tokenizer/index.js
- Comment update in tutorials/pci-tokenizer/src/app.js
- Comments updates in …

Multiple updates
