GoogleCloudPlatform/community

tutorials/run-laravel-on-appengine-flexible/index.md
A bug was fixed, so adding the socket manually is no longer required
=> Removes a deprecated step from Laravel

tutorials/setting-up-postgres-hot-standby.md
Because we create archive dir under  postgres working dir 
`$ mkdir -p ../../var/lib/postgresql/main/mnt/server/archivedir` -> `/var/lib/postgresql/main/mnt/server/archivedir` 
`archive_command` will fail to write in `/mnt/server/archivedir` dir.
=> Fix path for postgres archive command 

tutorials/developing-services-with-k8s.md
In the 0.26 version, Telepresence no longer requires Docker, so I'm deleting the references.
=> Remove Docker mention from tutorial

tutorials/developing-services-with-k8s.md
The tutorial that uses Telepresence was using outdated installation instructions.
I believe this submission should be covered by a corporate CLA that Richard Li filled out when he submitted the tutorial originally.
=> Switch to new installation instructions that don't hardcode a particular version

tutorials/oauth2-with-23andme-in-java/index.md, tutorials/oauth2-with-23andme-in-java/java/pom.xml, tutorials/oauth2-with-23andme-in-java/java/src/main/java/com/google/api/services/samples/ttam/Account.java, tutorials/oauth2-with-23andme-in-java/java/src/main/java/com/google/api/services/samples/ttam/Genotype.java, tutorials/oauth2-with-23andme-in-java/java/src/main/java/com/google/api/services/samples/ttam/Profile.java, tutorials/oauth2-with-23andme-in-java/java/src/main/java/com/google/api/services/samples/ttam/SimpleExample.java
Tagging @lesv regarding https://github.com/google/google-oauth-java-client/pull/140 .  I have ported my sample app to this repo and addressed your comments.
=> 23andMe API & google oauth2 - round trip working example w/ sickle cell anemia

tutorials/run-swift-kitura-on-google-cloud/Package.swift
The latest docker image is incompatible with 1.3, so the tutorial fails.
=> Update Kitura dependency to 1.7

tutorials/using-nodejs-to-calculate-the-size-of-a-bigquery-dataset/index.md
In the example code and beginning instructions, we use the file `index.js`.
=> Rename `size.js` to `index.js`

tutorials/ssh-tunnel-on-gce.md
Set up SSH tunnel for private browsing using GCE
https://cloud.google.com/community/tutorials/ssh-tunnel-on-gce
=> Fix gcloud command for ssh tunnel tutorial

tutorials/run-spring-petclinic-on-app-engine-cloudsql/index.md
removing Maven `pom.xml` sections from tutorial due to  incorrect rendering @ https://cloud.google.com/community/tutorials/run-spring-petclinic-on-app-engine-cloudsql
Added links to point directly to Maven central to allow users to retrieve latest version of libraries.
=> removing pom.xml snippets from tutorial

tutorials/cloud-functions-twilio-sms/index.js, tutorials/cloud-functions-twilio-sms/index.md, tutorials/cloud-functions-twilio-sms/package.json
Twilio updated the Node.js library to use slightly different syntax for a SMS response. See [here](https://twilio.github.io/twilio-node/3.0.0/MessagingResponse.html) for more detail. This PR updates the tutorial syntax to the latest version of their Node.js lib.
Also updated request validation to match voice response [tutorial](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/cloud-functions-twilio-voice-record/index.js#L127-L130). Happy to update that tutorial as well if needed.
=> Update Twilio SMS Tutorial to Twilio Node.js 3.x 

tutorials/symfony-hello-world-app-engine.md
The symfony tutorial was out-of-date, and changes in Symfony 3.3 make priming the cache before deployment possible, which is absolutely critical to App Engine Standard development on Symfony.
Additionally, I added a GCS sample to the helloworld project.
=> updates to symfony 3.3

tutorials/managing-gcp-projects-with-terraform/index.md
- Fixed bad reference to TF_BACKEND_BUCKET variable. when setting up remote state.
- Fixed invalid backed type, renamed from `cloud_storage` to `gcs`
- Added note to SSH setup regarding account access.
=> Fixes to tutorials/managing-gcp-projects-with-terraform

tutorials/managing-gcp-projects-with-terraform/index.md
gsutil within cloud shell does not identify a project from core.project (set by --set-as-default. 
Options are:
a) pass project with -p
b) run gcloud config set project ${TF_ADMIN}
I picked a.
=> Update index.md to force default project on gsutil

tutorials/setting-up-postgres.md
Some metrics from this page suggested that success rate was low, and that they were in fact searching for Cloud SQL for PostgreSQL. However, few if any actually clicked the link in the intro. I tried to make it stand out a bit more, and make it more obvious that it would be a way to get around having to install and maintain the database.
=> Update link to Cloud SQL to make the benefit more clear

tutorials/https-load-balancing-nginx/index.md
Replaced deprecated *gcloud compute copy-files* with *gcloud compute scp* for adding ssl files to nginx. Adding separate tasks for moving files to correct folder due to missing write access and scp not supporting root login on gcloud instances.
=> Uploading ssl files to nginx with scp

tutorials/appengine-dropwizard/example.pom.xml, tutorials/appengine-dropwizard/index.md
This tutorial shows how to deploy an [Apache Dropwizard](http://www.dropwizard.io) application on Google App Engine flexible environment.
=> New  Tutorial: Deploying Apache Dropwizard applications on Google App Engine

tutorials/managing-gcp-projects-with-terraform/index.md
`service-management` command group has been replaced - use `services` instead.
=> `service-management` command group replaced

tutorials/managing-gcp-projects-with-terraform/index.md
Someone who doesn't know the unix shell command well will find the following command to be hard to follow:
`eval $(terraform output  | awk -F' = ' '// {print "export " $1"="$2}')`
Replaced it with more 'readable' commands.
=> awk command is a bit obscure for a tutorial

tutorials/managing-gcp-projects-with-terraform/index.md
My terraform state file was just overwritten by a bad `terraform refresh`, and because versioning was not enabled, I lost thus the whole state. This change will hopefully prevent this horrible mistake in the future.
=> Add GCS versioning to terraform on GCP guide

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
This contains a few updates to the tutorial "Run an Elixir Phoenix app on Kubernetes using Google Container Engine", most notably to update names for the "Google Container Engine" -> "Google Kubernetes Engine" change. Specifically:
* Change all instances of "Container Engine" to "Kubernetes Engine".
* Change the title accordingly.
* Include a "next steps" link to configure static IP addresses.
=> Update Elixir-Kubernetes tutorial with new name for GKE

tutorials/elixir-phoenix-on-google-app-engine.md
The tutorial as originally written, covered deployments without using OTP releases. This was because the Elixir Runtime did not support releases at the time. However, release support has since been added to the runtime. And because use of OTP releases is strongly considered a deployment best practice in the Erlang and Elixir communities, we thought it best to update the tutorial to reference them, even if it lengthens the tutorial a bit. (Note that the corresponding tutorials for [GKE](https://cloud.google.com/community/tutorials/elixir-phoenix-on-kubernetes-google-container-engine) and [GCE](https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-compute-engine) already use OTP releases; indeed the new section on Distillery is largely copy-pasted from the GKE tutorial. Note …
=> Update Elixir-GAE tutorial to include distillery releases

tutorials/cloud-functions-github-auto-deployer/auto-deployer/index.js
I found this after trying to deploy the function in this tutorial and seeing:
`Error: Cannot find module './config2.json'`.
=> Fix config import path in Cloud Functions auto-deployer tutorial

tutorials/https-load-balancing-nginx/index.md
In the "Create your load balancer backends" section, step 1 creates instances with a startup-script to install and load apache2 on each instance. However, testing Apache on each instance subsequently fails ("Connection refused") apparently because the Apache service did not load correctly. I suspect the startup script can be improved by issuing the `service apache2 reload` command AFTER the `a2enmod` command.
=> Load apache after enabling modules

tutorials/appengine-serve-machine-learning-model/index.md
Accompanying tutorial for the sample app: https://github.com/GoogleCloudPlatform/ml-on-gcp/tree/master/sklearn/gae_serve.
=> New tutorial: serve machine learning models with App Engine and Cloud Endpoints

tutorials/elixir-phoenix-on-google-compute-engine/index.md
I received [feedback](https://github.com/GoogleCloudPlatform/elixir-runtime/issues/6#issuecomment-348820048) on this tutorial that it wasn't clear how Docker was being used. A reader thought that we were deploying Docker containers themselves to GCE (which is not considered good practice for Elixir apps) whereas we are actually using Docker only to do cross-compilation. This clarifies the language.
=> Clarify Docker usage in Elixir-GCE tutorial

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
This contains an update to the tutorial "Run an Elixir Phoenix app on Kubernetes using Google Container Engine". It changes the phrase "Google Container Engine API" -> "Google Kubernetes Engine API".
=> Update Elixir-Kubernetes tutorial with new name for container engine API.

tutorials/run-expressjs-on-google-app-engine.md
The goal of the _Run Express.js on Google App Engine_ tutorial is to create a very simple "Hello World" example without assuming much user knowledge. The deployed tutorial page in question can be found [here](https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine).
A. Users start with `npm init` and are given no guidance on how to use the interactive CLI. Most users will use the CLI's suggested defaults, which means that the application will set the entry point to `index.js`.
B. Before deployment, users are encouraged to use `npm start`, then open localhost:8080 to see their "Hello World" example. The instructions, however, do no provide instructions for adding such a command to the `package.json` file. `npm init` does not automatically add this command.
C. …
=> Simplify setup steps for Express on App Engine tutorial.

tutorials/https-load-balancing-nginx/index.md
I could not find the file named default-ssl on my instances; turns out it is named default-ssl.conf.
=> Update default-ssl config filename

tutorials/continuous-deployment-pipeline-google-container-engine-with-codeship/index.md, tutorials/developing-services-with-k8s.md, tutorials/elixir-phoenix-on-google-compute-engine/index.md, tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md, tutorials/envoy-flask-google-container-engine.md, tutorials/managing-gcp-projects-with-terraform/index.md, tutorials/modular-load-balancing-with-terraform/index.md, tutorials/run-botkit-on-google-container-engine/index.md, tutorials/run-spring-petclinic-on-app-engine-cloudsql/index.md, tutorials/running-nodejs-on-google-cloud.md, tutorials/transparent-proxy-and-filtering-on-k8s-with-initializers/index.md, tutorials/transparent-proxy-and-filtering-on-k8s/index.md
Also rename some links to https://cloud.google.com/container-engine/ and
the service account roles, which also have changed.
=> Replace "Container Engine" by "Kubernetes Engine".

tutorials/ghost-on-app-engine-part-1-deploying.md, tutorials/ghost-on-app-engine-part-2-monitoring.md
I've updated the tutorial for deploying Ghost on Google Cloud App Engine. I tried to follow the tutorial myself, but noticed that Ghost have changed some things, notably the config files. So I updated this tutorial with the process I used to deploy.
Major changes:
- Updated example config files
- Added an extra step that involves running knex-migrator with the 'production' flag set
=> Ghost on App Engine update

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
rm "The period at the end is required." because it is not
```
$ gcloud container builds submit --tag=gcr.io/<redacted>/phx_gcp_cluster:v1
Creating temporary tarball archive of 44 file(s) totalling 304.8 KiB before compression.
```
=> remove no longer required period

tutorials/horizontally-scale-mysql-database-backend-with-google-cloud-sql-and-proxysql/index.md
PostgreSQL is now out of [beta](https://cloudplatform.googleblog.com/2018/04/Cloud-SQL-for-PostgreSQL-now-generally-available-and-ready-for-your-production-workloads.html)
=> Remove BETA from PostgreSQL

tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md
Following the release of managed_rollout functionality to prod, we don't need beta anymore.
=> Removing beta from app deployment command

tutorials/run-symfony-on-appengine-flexible/index.md
Symfony 4 introduced a new directory structure: http://fabien.potencier.org/symfony4-directory-structure.html renaming `web` to `public`. The front controller was also unifed from app.php & app_dev.php to index.php. The APP_DEV environment variable is also required, for symfony 4.
I think this should resolve #372
=> Add configuration for Symfony 4

tutorials/managing-gcp-projects-with-terraform/index.md
a) terraform-admin.json isn't the name of the credentials that get downloaded for me.
b) the latest provider for gcs deprecates path for prefix. Should we adjust this?
=> Use proper credentials and latest gcs backend.

tutorials/understanding-oauth2-and-deploy-a-basic-auth-srv-to-cloud-functions/index.md
The link provides an absolute path to the code instead a relative one. If things get renamed, then this could break.
=> Fixing the link for download code

tutorials/cloud-functions-twilio-sms/index.md
Remove "beta" from the deployment commands, now that Cloud Functions are out of beta. Simplify deployment by not using a Cloud Storage bucket (which requires the user to read up on this topic in a separate doc).
=> Simplify deployment commands

tutorials/appengine-effective-polymodel.md, tutorials/appengine-pusher/index.md, tutorials/cdn-fastly.md, tutorials/cloud-functions-oauth-gmail/index.md, tutorials/cloud-iot-firestore-config/index.md, tutorials/cloud-iot-hybrid/index.md, tutorials/cloud-iot-logging/index.md, tutorials/cloudbuild-angular-universal/index.md, tutorials/developing-services-with-k8s.md, tutorials/envoy-flask-google-container-engine.md, tutorials/get-started-bitnami-django.md, tutorials/install-bower-dependencies-on-google-app-engine.md, tutorials/ios-chatbot-part-2/index.md, tutorials/ios-chatbot-part-3/index.md, tutorials/iot-device-to-device/README.md, tutorials/iot-device-to-device/index.md, tutorials/kubernetes-auth-openid-rbac.md, tutorials/on-beyond-magpie2.md, tutorials/puppet-in-google-cloud-platform.md, tutorials/run-botkit-on-google-container-engine/index.md, tutorials/setting-up-lemp.md, tutorials/setting-up-postgres-hot-standby.md, tutorials/setting-up-ruby-discourse.md, tutorials/ssh-port-forwarding-set-up-load-testing-on-compute-engine/index.md, tutorials/ssh-tunnel-on-gce.md, tutorials/styleguide.md, tutorials/using-cloud-vpn-with-alibaba-site-to-site/index.md, tutorials/using-cloud-vpn-with-cisco-asr/index.md, tutorials/wix-media-python.md
Reverts GoogleCloudPlatform/community#633
The HTML entities are still stripped from the documents during the publishing process. At least before #633, the angle brackets were preserved when viewing the files here on GitHub.
@dazuma , let's revisit this after the holiday weekend.
=> Revert "Escape or transform things that look like html tags in existing content"

tutorials/nodejs-mongodb-on-appengine.md
For issue #449. Existing code results in an error with more recent versions of the MongoDB driver. Added `{ useNewUrlParser: true }` to `MongoClient.connect()`. Changed `collection.insert()` to `collection.insertOne()` as the prior was deprecated. Updated `MongoClient.connect()` to return a client object rather than a db object.
=> Updated code to be compatible with 3.0 version of MongoDB driver

tutorials/run-laravel-on-appengine-flexible/index.md
The variable may be a leftover from a previous App Engine *standard* environment tutorial.
=> remove unused STORAGE_DIR env variable on Laravel flexible tutorial

tutorials/cloud-iot-gateways-rpi/index.md
fixed minor typo in the step that changes into this tutorial's directory
=> IoT Gateways: typo with the cd into repo step

tutorials/symfony-hello-world-app-engine.md
Is there a better way to do this? It's showing up in our search also, which is not great. 
https://cloud.google.com/docs/tutorials#php%20%22app%20engine%20standard%22
=> Mark php55 symfony tutorial as deprecated

tutorials/how-to-roll-your-app-engine-managed-vms-app-back-to-a-previous-version-part-1.md
This converts a codeblock to use the indentation style required by our quirky publishing system. I also fixed a couple of other minor issues.
=> fixing codeblock that appeared as regular text

tutorials/ghost-on-app-engine-part-2-monitoring.md
This converts codeblocks to use the indentation style required by our quirky publishing system. I also fixed a couple of other minor issues.
=> fixing codeblocks that rendered as body text

tutorials/zero-to-lamp-deploy-with-chef/index.md
Update service account name and key for the activate service account command on the chef-workstation instance. Name and key need to match the key that was created earlier
=> Update service account name and key

tutorials/cloud-iot-hybrid/index.md
Because the HTML sanitizer strips the angle brackets and their contents, I switched the placeholder in a codeblock to use square brackets.
Since I was in the file anyway, I fixed some of the bigger branding and style issues.
=> using square brackets instead of angle brackets

tutorials/cloud-iot-logging/index.md
Our HTML sanitizer strips angle brackets and things between them, so I replaced the angle brackets in placeholders with square brackets.
I also converted a link from HTML to Markdown.
While I was in the file, I fixed some branding problems and did some light copy-editing.
=> repalcing angle brackets with square brackets

tutorials/developing-services-with-k8s.md
Because our HTML sanitizer strips angle brackets and the contents between them, I escaped a couple of sets of them.
While I was in the file, I fixed a few copy-editing issues.
=> escaping angle brackets

tutorials/docker-compose-on-container-optimized-os.md
This fixes an issue "Error response from daemon: error while creating
mount source path
'/rootfs/home/bargachayoub/developer-edition/configs/core.ini': mkdir
/rootfs: read-only file system".
Also, update the tag to the latest version (1.24.0).
Closes #583.
=> fix: Remove read-only /rootfs from docker command

tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md
fix error [app.yaml] Unexpected attribute 'Runtime' for object of type AppInfoExternal.
=> Fix typo in Runtime to runtime on line 239

tutorials/create-cloud-build-image-factory-using-packer/index.md
A new cloud build service account was introduced that breaks this command.
=> Patch for new cloud build service account.

tutorials/getting-started-on-gcp-with-terraform/index.md
Updating the example for Terraform 0.12 syntax.
Adding a caveat that users will need to wait for default firewalls to be set up.
Discovered in https://github.com/GoogleCloudPlatform/community/issues/883
=> Terraform tutorial update

tutorials/nginx-ingress-gke/index.md
Add `publishService` to publish the right ip in ingress resources.
The tutorial does not include the `controller.publishService.enabled` flag for installation of nginx-ingress. Without this flag a wrong IP will be published in the status of the ingress resource. 
This is documented in [issue 4092 on nginx-ingress](https://github.com/kubernetes/ingress-nginx/issues/4092). See also the [nginx-ingress Readme](https://github.com/helm/charts/blob/master/stable/nginx-ingress/README.md#configuration).
See also #891
=> Update nginx-ingress-gke tutorial

tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
Minor nit: Args is spaced incorrectly for the yaml file and will lead to a build error when running "gcloud builds submit".
=> Fix formatting error for elixir sample with cloud build

tutorials/getting-started-on-gcp-with-terraform/index.md
Following [Managing SSH Keys in Metadata](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys) guidelines the metadata key should be `ssh-keys` and not `sshKeys`
=> Fix metadata key for SSH keys

tutorials/standalone-tensorflow-raspberry-pi/index.md
The linked tutorial will be removed from the AI Platform docs soon.
Additionally, "Cloud Machine Learning Engine" has been renamed.
=> Remove link to soon-to-be-deleted tutorial

tutorials/cloud-run-local-dev-docker-compose/index.md
GOOGLE_CLOUD_PROJECT is not part of the Cloud Run container contract: https://cloud.google.com/run/docs/reference/container-contract#env-vars
=> Remove GOOGLE_CLOUD_PROJECT env var

tutorials/understanding-oauth2-and-deploy-a-basic-auth-srv-to-cloud-functions/index.md
The link to the OAuth 2.0 RFC was pointing at RFC 6479 (IPsec Anti-Replay Algorithm without Bit Shifting) instead RFC 6749 (The OAuth 2.0 Authorization Framework). I've fixed the text and the link
=> Fix incorrect OAuth 2.0 RFC link

tutorials/cloud-iot-firestore-config/functions/package.json
Fix `Engines field is required but was not found in functions/package.json.` error. Same fix as https://github.com/firebase/quickstart-js/pull/335
=> Add "engines" key to functions/package.json

tutorials/cloud-iot-gateways-rpi/index.md
Should resolve future issues that people have similar to #954 and #960.
* Add instructions for setting up virtual environments
* Improved wording for using raspberry pi
=> iot: add virtual environment setup instructions for gateway tutorial

tutorials/deploy-grails-to-google-cloud/index.md
Cloud SQL now runs MySQL 5.7. I found I had to update the drivers to match it.
=> Runtime dependencies updated to match Cloud SQL MySQL version.

tutorials/elixir-phoenix-on-google-app-engine.md, tutorials/elixir-phoenix-on-kubernetes-google-container-engine/.dockerignore, tutorials/elixir-phoenix-on-kubernetes-google-container-engine/Dockerfile, tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md
Updates the Elixir-Phoenix on GKE tutorial to reflect changes in Distillery 2.1 and Elixir 1.9. These are basically the same changes as in #968 (along with adjustments found when writing and testing #971).
=> Update GKE-Elixir tutorial to cover changes in Elixir 1.9

tutorials/deploy-grails-to-google-cloud/index.md
I found google-cloud-storage:1.2.3 resulted in method-overloading exceptions when calling storage.create() with no 'options'.
Upgrading to version 1.84.0 solved the issue.
=> Updated google-cloud-storage dependency version.

tutorials/cloud-functions-firestore/index.md
Change wording from "datastore mode" to Cloud Firestore in Native mode, and linked to comparison doc.
=> fixes #993 Change wording Firestore in Native mode

tutorials/bigquery-from-excel/index.md
BigQuery is the approved name.
I left the Excel UI text ("Google BigQuery") unchanged, since that occurrence is for UI steps.
=> Changes 'Google BigQuery' to 'BigQuery'.

tutorials/appengine-pusher/java/pom.xml
details about the vulnerability:
https://github.com/advisories/GHSA-mx7p-6679-8g3q
=> fixing security vulnerability

tutorials/run-spring-petclinic-on-app-engine-cloudsql/index.md
fix for this issue:
https://github.com/GoogleCloudPlatform/community/issues/1064
For Spring Boot 2.0 and higher, the following change must be made:
-Drun.profiles
goes to
-Dspring-boot.run.profiles
See the Spring Boot documentation for the current correct format for the command:
https://docs.spring.io/spring-boot/docs/current/maven-plugin/examples/run-profiles.html
=> updating command for starting Spring Boot

tutorials/cloud-iot-prometheus-monitoring/index.md, tutorials/continuous-deployment-pipeline-google-container-engine-with-codeship/index.md, tutorials/gke-networking-fundamentals/index.md
The three files in this PR are trying to print `{{ text }}` as part of the
tutorial text, which the template engine interprets as Django variables. The
`{{ text }}` should be printed as is.
Per the Django documentation, we can use the [`{{ verbatim }}`][0] tag to stop
the template engine from rendering the contents of this block tag.
[0]: https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#verbatim
=> Escapes brackets that are interpreted as Django tags.

tutorials/getting-started-on-gcp-with-terraform/index.md
change `instace` to `instance` in section `Add SSH access to the Compute Engine instance`
=> fix minor typo in GCP Terraform Tutorial

tutorials/docker-gcplogs-driver/index.md
When investigating #220, I found a few links that needed updating.
=> update docker-gcplogs-driver links

tutorials/using-cloud-vpn-with-strongswan/index.md
If we don't have `krt_prefsrc` (adds src to routes exported to kernel) testing connectivity from strongSwan VM won't be possible. Packets sent to the VMs on the CloudVPN Side will have `source` address of the VTI interface (which is not routable back for instances behind CloudVPN).
The `krt_prefsrc` option adds source to learned routes, in that case routes will be origination from strongSwan VM local interface (going then through VTI interface) and will be routable back. 
Summing that up: it makes it possible to access GCE instances (ping/ssh etc) behind CloudVPN from strongSwan VM itself. All the connectivity for the instances routed through strongSwan VM will be still working.
=> Add krt_prefsrc to the export filter of bird

.github/CONTRIBUTING.md
There is a bug in CONTRIBUTING.md where the text appears as below instead of clickable text:
- [individual CLA] (https://developers.google.com/open-source/cla/individual)
- [corporate CLA] (https://developers.google.com/open-source/cla/corporate)
This fix makes it such that the text "individual CLA" and "corporate CLA" are clickable and direct to their respective urls
=> Fix License Agreement links in CONTRIBUTING.md

tutorials/cloud-iot-enviro-board-workshop/enviro-device/cloud_config_template.ini, tutorials/cloud-iot-enviro-board-workshop/index.md
The current set device configuration step is broken. This fixes the issue and makes the environment variable substitution easier.
=> fix device configuration with environment variable

tutorials/modular-load-balancing-with-terraform/index.md
Moving the Terraform snippets in the modular-load-balancing-with-terraform tutorial to 0.12 style syntax.
=> Updating terraform examples for 0.12 syntax

tutorials/appengine-ruby-rails-activejob-pubsub.md
If this check stays in place, then the app can't be deployed:
https://cloud.google.com/appengine/docs/flexible/ruby/migrating-to-split-health-checks
=> removed legacy health check

tutorials/deploy-grails-to-google-cloud/index.md
Before removing it the following error was thrown:
`ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Legacy health checks are no longer supported for the App Engine Flexible environment. Please remove the 'health_check' section from your app.yaml and configure updated health checks. For instructions on migrating to split health checks see https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks`
=> Removed legacy health check configuration.

tutorials/dataflow-debug-oom-conditions/index.md
Some Java classes can throw `OutOfMemoryError` when the Java heap memory is enough. Dataflow users must check if their job hits this case before headump analysis.
=> Add a case that a class throws OOM with enough java heap

tutorials/deploy-react-nginx-cloud-run/index.md
Fixed syntax of gcloud cmd to build container.
was:
gcloud build submit --tag gcr.io/[YOUR_PROJECT_ID]/cra-cloud-run
changed to:
gcloud builds submit --tag gcr.io/[YOUR_PROJECT_ID]/cra-cloud-run
As reported by gcloud:
ERROR: (gcloud) Invalid choice: 'build'.
Maybe you meant:
gcloud builds submit
=> fixed syntax for gcloud builds cmd.

tutorials/cloud-spanner-commit-timestamp-change-log/index.md
copy-edit, branding fixes, and making steps and code not run into paragraphs
=> copy-edit, making steps and code not run into paragraphs

tutorials/network-throughput.md
This is an attempt to get past an apparent bug in the CircleCI lint tests for the frontmatter.
This PR is based off of the changes in this PR:
https://github.com/GoogleCloudPlatform/community/pull/1228
=> incorporating changes from Bernie in fresh PR

tutorials/dlp-to-datacatalog-tags/index.md
Fixes typo in the example command line under "Execute the script"
=> Fix typo sample command under "Execute the script"

tutorials/kube-mqtt/refresher-container/Dockerfile, tutorials/kube-mqtt/refresher-container/requirements.txt
There are issues getting the cryptography library to build in updated base alpine images - switching to standard python docker image
=> update for errors with alpine and py cryptography

tutorials/write.md
I know this link is meant to reference the Contributor license agreements, but for some reason it doesn't seem to work on the google tutorials page. Which leave the user trying to click and wondering why it doesn't work. Would be much better to put a link to the cla about page, as it is well explained and easy to navigate between individual and corporate CLAs.
=> Proposed change to the "View the cla" link.

tutorials/deploy-ha-vpn-with-terraform/index.md, tutorials/getting-started-on-gcp-with-terraform/index.md, tutorials/managing-gcp-projects-with-terraform/index.md, tutorials/modular-load-balancing-with-terraform/index.md
Link to the GCP with Terraform docs for easier discoverability/details: https://cloud.google.com/docs/terraform
This is a new page which we want to promote as the central hub for Terraform + GCP docs.
=> Add link to central Terraform docs.

tutorials/getting-started-on-gcp-with-terraform/index.md
This is meant to help users that have different versions of Terraform as the HCL syntax evolved significantly in the 0.12 release.
fixes https://github.com/GoogleCloudPlatform/community/issues/1234
=> Add caveat for Terraform version used

tutorials/dlp-to-datacatalog-tags/src/main/java/com/example/dlp/DlpDataCatalogTagsTutorial.java
Some updates on this tutorial:
1 - Added a fix to the code
When all DLP findings for a given Table was below the minimum threshold set at runtime, it would create a empty batch client call, generating an error message.
2 - Improved logging to help users troubleshoot this scenario.
Example:
`
>> Column [city] has findings
>> Findings for [city] has threshold 7 when minimum threshold is 100
>> Column [county] has findings
>> Findings for [county] has threshold 11 when minimum threshold is 100
>> Column [first_name] has findings
>> Findings for [first_name] has threshold 61 when minimum threshold is 100
>> Column [phone] has findings
>> Findings for [phone] has threshold 99 when minimum threshold is 100
>> Column [email] has findings
>> Findings for [email] has threshold 99 when minimum …
=> Edit - Community Tutorial: inspect BigQuery with DLP and integrate with Data Catalog

tutorials/cloud-functions-cloudbuild/cloudbuild.yaml, tutorials/cloud-functions-cloudbuild/code/function.go, tutorials/cloud-functions-cloudbuild/index.md
I wrote a tutorial how to use cloud build to deploy a cloud function to GCP. It deploys a public HTTP endpoint using cloud build and CI/CD. My original repository is (or was) at this link https://github.com/montao/faas-cicd
Feel free to ask me anything about it if there are any questions.
=> Add tutorial for cloud function with cloud build

tutorials/gke-workload-id-clientserver/index.md
I've gone through the tutorial, except for the `Cloud Run Invoker IAM authorization` section. I've updated a couple of the commands here so that they work.
=> Update workload tutorial's cluster create, kubectl delete commands

tutorials/nginx-ingress-gke/index.md
Updated this tutorial to align with k8s changes in recent versions. For e.g: 
This command no longer creates a deployment, but a pod.
```
kubectl run hello-app --image=gcr.io/google-samples/hello-app:1.0 --port=8080
```
=> papudatta updated index.md

tutorials/schedule-dataflow-jobs-with-cloud-scheduler/scheduler-dataflow-demo/terraform/main.tf
1) Grant cloud-scheduler-demo service account "Dataflow Worker" IAM role, which is needed to manage GCE resources used by Dataflow.  Alternatives are either to:
a) Grant "Service Account User" role for cloud-scheduler-demo to the default GCE service account, or 
b) Create a separate service account altogether with the "Dataflow Worker" IAM role, and specify this in (2).
2) Include "serviceAccountEmail" in the Dataflow template paramters.  You can omit this if you've granted "Service Account User" to cloud-scheduler-demo for the default GCE service account.
=> Allow service account to launch Dataflow job

tutorials/python-vision-quickstart.md
This PR updates the base location of the quickstart referenced in this tutorial. 
Location of example changed in https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4765
This tutorial is also accessed via https://cloud.google.com/vision/docs/label-detection-tutorial
=> Update location of sample code for python-vision-quickstart

tutorials/getting-started-on-gcp-with-terraform/index.md
Adding instructions to specify what role the service account will need to continue the tutorial.
fixes https://github.com/GoogleCloudPlatform/community/issues/1323
=> Add service account role instructions

tutorials/embedded-c-getting-started/index.md
It looks like this single `openssl` command should actually be two separate commands.
=> Add a missing line break.

tutorials/speech2srt/speech2srt.py
Used the 2.0.0 migration guide https://github.com/googleapis/python-speech/blob/master/UPGRADING.md#enums-and-types
nanos not found in datetime.timedelta, used microseconds instead.
Converted to milliseconds.
=> Updated speech2srt

tutorials/dataflow-debug-oom-conditions/index.md
Updated amount of memory available to user code across different types of worker machines. It is now ~70% of the installed amount in all cases.
=> Updated amount of memory available to user code.

tutorials/automl-tables-model-export/index.md
Adds a note re: the Cloud Run issue (which needs more time to be debugged), plus a clarification that the tutorial applies to  'CAIP AutoML', not 'uCAIP Tabular'.  The process is a little different for that and I'll update the tutorial to include both in a later PR.
=> added notes to the automl model export tutorial, particularly re: cloud run image issue

tutorials/using-flask-login-with-cloud-datastore/index.md
Docs now show this method as `get_obj` not `get_object`: https://datastore-entity.readthedocs.io/en/latest/#retrieving-entity-as-object
=> get_object -> get_obj per documentation

tutorials/gcp-cos-clamav/Dockerfile, tutorials/gcp-cos-clamav/build, tutorials/gcp-cos-clamav/conf/clamd.conf, tutorials/gcp-cos-clamav/index.md, tutorials/gcp-cos-clamav/scan.sh, tutorials/gcp-cos-clamav/start.py
Inspired by PR #1597, this switches the scanning application from clamscan to clamdscan. The daemon clamd was already running, so now we're using it.
Moved the clamscan command line args into the clamd config file.
Updated readme
Added the ability for custom configs that live outside the container
Added the ability to gracefully recover from an incomplete scan
=> Convert clamav scanner from clamscan to clamdscan

tutorials/dataflow-debug-oom-conditions/index.md
Added clarification to Dataflow OOM article on the number of threads started by Dataflow.
The changes to the content are in lines 247 - 261. 
The Markdown editor I used (Atom) seems to have deleted some extra blank space elsewhere in the file, but there are no other changes to the information presented in the article.
=> Added more information on the number of threads started by Dataflow in Streaming pipelines.

tutorials/horizontally-scale-mysql-database-backend-with-google-cloud-sql-and-proxysql/index.md
https://cloud.google.com/community/tutorials/horizontally-scale-mysql-database-backend-with-google-cloud-sql-and-proxysql
Fixes https://github.com/GoogleCloudPlatform/community/issues/1589
=> Updates table name in mysql tutorial

tutorials/auto-bigquery-tokenize/index.md, tutorials/auto-data-tokenize/index.md
using plain `gradle` results in inconsistent builds due to dependence on local gradle version. update instructions to use `gradlew` for using [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) for consistent builds.
=> Instructions to use gradlew for consistent build

tutorials/secrets-manager-python/index.md
Hello! I was browsing the Secret Manager Python tutorial and spotted a typo. Figured I'd submit a small fix.
=> Fix a typo in the secret manager python tutorial

tutorials/developing-services-with-k8s.md
The provided macOS commands do not work with the most recent version of Homebrew 3.*.
Due to this, I provided the correct instructions for the most recent version of Homebrew as well as clarified which version of the command is used.
=> Update documentation to support Homebrew 3.*

tutorials/bigquery-ibis/ibis_bigquery.py, tutorials/bigquery-ibis/index.md
The version on GitHub is currently broken, but also it's a best practice
to install from release where possible.
Closes #1735
=> bigquery-ibis: install ibis-framework from published packages

tutorials/cloud-iot-prometheus-monitoring/index.md
Starting with [GKE node version 1.19](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd#:~:text=starting%20with%20gke%20node%20version%201.19), COS image type is deprecated. I suggest to not explicitly specify any parameters where defaults would work.
=> Do not explicitly specify COS where not needed

tutorials/cicd-cloud-run-github-actions/index.md
Hi,
Thank you for great tutorial, and it has really helped me. However, since I found one mistake in it, I fixed it.
As for `Login` step in `GCP-Deploy.yml`, you provide `GCP_PROJECT_ID` as the input. This setting did not work for me, and warnings like below were appeared.
```bash
Unexpected input(s) 'GCP_PROJECT_ID', valid inputs are ['version', 'service_account_email', 'service_account_key', 'project_id', 'export_default_credentials', 'credentials_file_path']
```
After I changed `GCP_PROJECT_ID` into `project_id` in accordance with the warnings, it worked for me. Thank you for your check in advance.
=> PR with tutorials/cicd-cloud-run-github-actions/index.md

tutorials/dlp-hybrid-inspect/index.md
Fix: Add missing step to clone the repository to compile and run the code in the tutorial
=> Add repository cloning step in dlp-hybrid-inspect

tutorials/appengine-ruby-rails-activejob-sidekiq.md
I felt that the docs were lacking in terms of offering users multiple ways of dealing with the Redis credentials, and seeing the default option being supplying plaintext passwords and secret keys in a `yaml` file was somewhat concerning.
Included some steps that users that chose the `foreman` option could take to securely provide their apps with the Redis IP address & passwords without exposing them in plaintext via the Rails `credentials.enc.yml` file. It involves users creating an initializer for Sidekiq, where they will pass the encrypted variables that way.
=> Improve Redis/Sidekiq integration docs

tutorials/singularity-containers-with-cloud-build/index.md
The Singularity Cloud Build tutorial is missing basic instructions to clone the repository and cd into the correct folder with the tutorial information, as reported here: https://github.com/GoogleCloudPlatform/community/issues/1627. This pull request will fix that.
I just noticed that I don't have a cd into the repository folder, so we can add that too.
=> Add instruction to clone tutorial to singularity cloud build

tutorials/kubernetes-engine-customize-fluentbit/kubernetes/fluentbit-daemonset.yaml
the stackdriver plugin has bugs that cause the tutorial to fail that
have been fixed in 1.8. Particularly:
https://github.com/fluent/fluent-bit/pull/3330/files
=> update fluentbit version from 1.6 to 1.8

tutorials/sql-server-ao-single-subnet/index.md
The following property : "request" is not needed. If this property it populated then the response property also needs to be populated. 
If the request and response don't match then amber lights appear on the load balancer UI (rather than one green and one amber - desired). Listener resolution is also impacted, resulting in timeouts and longer time to failover / failback.
Let's keep both the request and response properties of the healthcheck blank to avoid load balancer  / hc issues. 
ref: https://cloud.google.com/load-balancing/docs/health-check-concepts?&_ga=2.139983091.-1312798538.1627908672#criteria-protocol-ssl-tcp
Change:  removed the following: 
--request=10.128.0.20 \
=> removed request property from healthcheck

tutorials/dlp-hybrid-inspect/index.md
On a brand new VM, for example, these won't already be installed, so it's helpful to include this step for those running through the demo.
=> Include a step in dlp hybrid inspect demo to install git/maven

tutorials/developing-services-with-k8s.md
The [Locally developing microservices with Google Kubernetes Engine](https://cloud.google.com/community/tutorials/developing-services-with-k8s) tutorial contains commands that were used in Telepresence 1 instead of the current default version (Telepresence 2). This means that any reader who follows the instructions in this tutorial will not achieve its intended goal.
This pull request adds the current commands and modifies its description. Please review!
=> Tutorial update: Locally developing microservices with Google Kubernetes Engine

tutorials/migrate-oracle-postgres-using-datastream/index.md
switching the reference to the new Dataflow template, which also requires one added param `schemaMap`
=> Switch to new Dataflow template

tutorials/stackdriver-monitor-slow-query-mysql/index.md
See https://cloud.google.com/logging/docs/agent/installation for the latest installation instructions.
=> Fix deprecated logging agent install script.

tutorials/cicd-cloud-run-github-actions/index.md
Replace `GoogleCloudPlatform/github-actions/setup-gcloud@master` in the sample YAML by `google-github-actions/setup-gcloud@master` which is the new working repo path for this action
Closes #2018
=> fix: #2018 put google-github-actions on Login step

tutorials/deploy-dependency-track/demo-project/pyproject.toml
addresses this vulnerability:
https://github.com/advisories/GHSA-v6rh-hp5x-86rv
=> updating version of Django

tutorials/setting-up-postgres.md
In Create a Compute Engine Instance Section
Step 4 has a typo that says Book disk rather than Boot Disk.
=> Fixed Typo In Compute Engine Instance Section

tutorials/antho-bare-metal-getting-started.md
The .secrets field within service accounts is only for listing secrets
to be mounted into pods, not for extracting secrets for other uses.
There is no guarantee the first item in the list will be a token secret.
In 1.24+, this field is not populated by default.
Adapt instructions from https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token to obtain a token
=> Fix method of obtaining service account token

tutorials/artifactory-gcs-setup/index.md
Change storage/docs/quickstarts to storage/docs/introduction#quickstarts and storage/docs/key-terms#buckets to storage/docs/buckets.
CLs that introduced these changes:
* https://critique.corp.google.com/cl/464602262
* https://critique.corp.google.com/cl/470022707
=> Update broken links

tutorials/bigquery-ibis/ibis_bigquery_sample.py, tutorials/bigquery-ibis/index.md
* Sample file renamed so as not to conflict with the `ibis-bigquery` package.
* Data types are no longer accepted as strings. One must pass in a data type object.
* UDF import changed to pull from `ibis-bigquery` package.
=> fix: update bigquery-ibis sample to work on latest ibis-bigquery package

tutorials/speech2srt/speech2srt.py
start_time and end_time are already datetime.timedeltas
Fixes:
> start = w.start_time.ToTimedelta()
> AttributeError: 'datetime.timedelta' object has no attribute 'ToTimedelta'
=> speech2srt: fix broken conversion

tutorials/web-instrumentation/index.md
The link https://cloud.google.com/solutions/identifying-causes-of-app-latency-with-stackdriver-and-opencensus is no longer valid. It redirects to https://cloud.google.com/trace/docs/trace-app-latency, or it will in the next few days.
=> Update file to remove deprecated link

tutorials/migrate-oracle-postgres-using-datastream/ora2pg/Ora2PGDockerfile
New DBD::Oracle build fail because of the oracle instantclient lib symbol link and need Test::NoWarnings perl module.
=> DBD::Oracle build fail workaround

tutorials/deploy-dependency-track/deploy/frontend/ingress.yaml
apiVersion: networking.k8s.io/v1beta1 is not supported anymore. Using apiVersion: networking.k8s.io/v1
=> apiVersion not supported any more

tutorials/pci-tokenizer/package.json
This is required by [`server.js`](https://github.com/GoogleCloudPlatform/community/blob/3bba105feb1e2908e966c1bd408ec1c8f4842bbd/tutorials/pci-tokenizer/src/server.js#L12), but not included in the `package.json` file.
Starting the server without this produces the error:
> Error: Cannot find module 'body-parser'
=> [pci-tokenizer] Add "body-parser" to package.json
